In [1]:
from sklearn import datasets
print(datasets.__all__)

['clear_data_home', 'dump_svmlight_file', 'fetch_20newsgroups', 'fetch_20newsgroups_vectorized', 'fetch_lfw_pairs', 'fetch_lfw_people', 'fetch_mldata', 'fetch_olivetti_faces', 'fetch_species_distributions', 'fetch_california_housing', 'fetch_covtype', 'fetch_rcv1', 'fetch_kddcup99', 'get_data_home', 'load_boston', 'load_diabetes', 'load_digits', 'load_files', 'load_iris', 'load_breast_cancer', 'load_linnerud', 'load_mlcomp', 'load_sample_image', 'load_sample_images', 'load_svmlight_file', 'load_svmlight_files', 'load_wine', 'make_biclusters', 'make_blobs', 'make_circles', 'make_classification', 'make_checkerboard', 'make_friedman1', 'make_friedman2', 'make_friedman3', 'make_gaussian_quantiles', 'make_hastie_10_2', 'make_low_rank_matrix', 'make_moons', 'make_multilabel_classification', 'make_regression', 'make_s_curve', 'make_sparse_coded_signal', 'make_sparse_spd_matrix', 'make_sparse_uncorrelated', 'make_spd_matrix', 'make_swiss_roll', 'mldata_filename']

In [3]:
import numpy as np
dataset = np.loadtxt("pl.tsv", dtype={'names': ('name', 'year'), 'formats': ('U100', 'i4')},
   skiprows=1, delimiter="\t", encoding="UTF-8")
print(dataset)

[('ENIAC coding system', 1943) ('ENIAC Short Code', 1946)
 ('Von Neumann and Goldstine graphing system', 1946)
 ('ARC Assembly', 1947) ('Plankalkül', 1948) ('CPC Coding scheme', 1948)
 ('Curry notation system', 1948) ('Short Code', 1949)
 ('assembly language', 1949) ('Short Code', 1950)
 ('Birkbeck Assembler', 1950) ('G-code', 1950) ('Superplan', 1951)
 ('ALGAE', 1951) ('Intermediate Programming Language', 1951)
 ('Regional Assembly Language', 1951)
 ('Boehm unnamed coding system', 1951) ('Klammerausdrücke', 1951)
 ('OMNIBAC Symbolic Assembler', 1951) ('Stanislaus', 1951)
 ('Whirlwind assembler', 1951) ('Rochester assembler', 1951)
 ('Sort Merge Generator', 1951) ('Editing Generator', 1952)
 ('COMPOOL', 1952) ('autocode', 1952) ('A-0 System', 1952)
 ('READ/PRINT', 1953) ('Speedcoding', 1953) ('Fortran', 1954)
 ('MATRIX MATH', 1954) ('autocode', 1954) ('ARITH-MATIC', 1954)
 ('Laning and Zierler system', 1954) ('MATH-MATIC', 1954)
 ('FLOW-MATIC', 1955) ('BACAIC', 1955) ('Freiburger Code', 1955)
 ('Sequentielle Formelübersetzung', 1955) ('Internal Translator', 1955)
 ('PRINT', 1955) ('PACT', 1955) ('Information Processing Language', 1956)
 ('FORTRAN for the IBM 704', 1956) ('Fortran', 1957) ('UNICODE', 1957)
 ('COMTRAN', 1957) ('GEORGE', 1957) ('ALGOL 58', 1958) ('Lisp', 1958)
 ('FORTRAN III', 1958) ('FORTRAN II', 1958) ('ALGOL', 1958)
 ('JOVIAL', 1959) ('TRAC', 1959) ('COBOL', 1959) ('Lisp', 1959)
 ('MAD', 1959) ('FACT', 1959) ('COBOL', 1960) ('COBOL', 1960)
 ('ALGOL 60', 1960) ('ALCOR', 1960) ('FORTRAN IV', 1961) ('SNOBOL', 1962)
 ('TECO', 1962) ('Simula', 1962) ('APL', 1962) ('CORC', 1962)
 ('CPL', 1963) ('JOSS', 1963) ('P′′', 1964)
 ('Report Program Generator', 1964) ('TRAC', 1964) ('BASIC', 1964)
 ('COWSEL', 1964) ('PL/I', 1964) ('MARK IV', 1964) ('MIMIC', 1964)
 ('Speakeasy', 1964) ('IBM RPG II', 1965) ('Atlas Autocode', 1965)
 ('TELCOMP', 1965) ('Euler', 1966) ('ISWIM', 1966) ('ALGOL W', 1966)
 ('JOSS', 1966)
 ('Massachusetts General Hospital Utility Multi-Programming System', 1966)
 ('BCPL', 1966) ('Coral 66', 1966) ('FORTRAN 66', 1966) ('APL', 1966)
 ('Hop', 1967)
 ('Massachusetts General Hospital Utility Multi-Programming System', 1967)
 ('Space Programming Language', 1967) ('BCPL', 1967) ('Interlisp', 1967)
 ('Simula', 1967) ('XPL', 1967) ('PILOT', 1968)]

In [4]:
from pandas.io.json import json_normalize
import pandas as pd
import json

data = json.load(open('pl.json'))
dataframe = json_normalize(data)
print(dataframe)

                                        languageLabel  year
0                                 ENIAC coding system  1943
1                                    ENIAC Short Code  1946
2           Von Neumann and Goldstine graphing system  1946
3                                        ARC Assembly  1947
4                                          Plankalkül  1948
5                                   CPC Coding scheme  1948
6                               Curry notation system  1948
7                                          Short Code  1949
8                                   assembly language  1949
9                                          Short Code  1950
10                                 Birkbeck Assembler  1950
11                                             G-code  1950
12                                          Superplan  1951
13                                              ALGAE  1951
14                  Intermediate Programming Language  1951
15                         Regional Assembly Language  1951
16                        Boehm unnamed coding system  1951
17                                   Klammerausdrücke  1951
18                         OMNIBAC Symbolic Assembler  1951
19                                         Stanislaus  1951
20                                Whirlwind assembler  1951
21                                Rochester assembler  1951
22                               Sort Merge Generator  1951
23                                  Editing Generator  1952
24                                            COMPOOL  1952
25                                           autocode  1952
26                                         A-0 System  1952
27                                         READ/PRINT  1953
28                                        Speedcoding  1953
29                                            Fortran  1954
..                                                ...   ...
70                                               JOSS  1963
71                                                P′′  1964
72                           Report Program Generator  1964
73                                               TRAC  1964
74                                              BASIC  1964
75                                             COWSEL  1964
76                                               PL/I  1964
77                                            MARK IV  1964
78                                              MIMIC  1964
79                                          Speakeasy  1964
80                                         IBM RPG II  1965
81                                     Atlas Autocode  1965
82                                            TELCOMP  1965
83                                              Euler  1966
84                                              ISWIM  1966
85                                            ALGOL W  1966
86                                               JOSS  1966
87  Massachusetts General Hospital Utility Multi-P...  1966
88                                               BCPL  1966
89                                           Coral 66  1966
90                                         FORTRAN 66  1966
91                                                APL  1966
92                                                Hop  1967
93  Massachusetts General Hospital Utility Multi-P...  1967
94                         Space Programming Language  1967
95                                               BCPL  1967
96                                          Interlisp  1967
97                                             Simula  1967
98                                                XPL  1967
99                                              PILOT  1968

[100 rows x 2 columns]

In [6]:
import urllib.request
import json
import pandas as pd

url = "https://query.wikidata.org/sparql?query=SELECT%20%3FlanguageLabel%20(YEAR(%3Finception)%20as%20%3Fyear)%0AWHERE%0A%7B%0A%20%20%23instances%20of%20programming%20language%0A%20%20%3Flanguage%20wdt%3AP31%20wd%3AQ9143%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20wdt%3AP571%20%3Finception%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20rdfs%3Alabel%20%3FlanguageLabel.%0A%20%20FILTER(lang(%3FlanguageLabel)%20%3D%20%22en%22)%0A%7D%0AORDER%20BY%20%3Fyear%0ALIMIT%20100&format=json"
response = urllib.request.urlopen(url)
responsedata = json.loads(response.read().decode('utf-8'))

array = []

for data in responsedata['results']['bindings']:
  array.append([data['year']['value'], data['languageLabel']['value']])
dataframe = pd.DataFrame(array, columns=['year', 'languageLabel'])
print(dataframe)
dataframe = dataframe.astype(dtype= {"year":"<i4", "languageLabel":"<U200"})

    year                                      languageLabel
0   1943                                ENIAC coding system
1   1946                                   ENIAC Short Code
2   1946          Von Neumann and Goldstine graphing system
3   1947                                       ARC Assembly
4   1948                                         Plankalkül
5   1948                                  CPC Coding scheme
6   1948                              Curry notation system
7   1949                                         Short Code
8   1949                                  assembly language
9   1950                                         Short Code
10  1950                                             G-code
11  1950                                 Birkbeck Assembler
12  1951                               Sort Merge Generator
13  1951                                          Superplan
14  1951                                              ALGAE
15  1951                  Intermediate Programming Language
16  1951                         Regional Assembly Language
17  1951                        Boehm unnamed coding system
18  1951                                   Klammerausdrücke
19  1951                         OMNIBAC Symbolic Assembler
20  1951                                         Stanislaus
21  1951                                Whirlwind assembler
22  1951                                Rochester assembler
23  1952                                         A-0 System
24  1952                                           autocode
25  1952                                  Editing Generator
26  1952                                            COMPOOL
27  1953                                        Speedcoding
28  1953                                         READ/PRINT
29  1954                                            Fortran
..   ...                                                ...
70  1963                                               JOSS
71  1964                                                P′′
72  1964                           Report Program Generator
73  1964                                               TRAC
74  1964                                              BASIC
75  1964                                             COWSEL
76  1964                                          Speakeasy
77  1964                                               PL/I
78  1964                                            MARK IV
79  1964                                              MIMIC
80  1965                                         IBM RPG II
81  1965                                     Atlas Autocode
82  1965                                            TELCOMP
83  1966                                              ISWIM
84  1966                                            ALGOL W
85  1966                                              Euler
86  1966                                               JOSS
87  1966  Massachusetts General Hospital Utility Multi-P...
88  1966                                           Coral 66
89  1966                                                APL
90  1966                                               BCPL
91  1966                                         FORTRAN 66
92  1967                                                Hop
93  1967  Massachusetts General Hospital Utility Multi-P...
94  1967                                                XPL
95  1967                                          Interlisp
96  1967                                             Simula
97  1967                                               BCPL
98  1967                         Space Programming Language
99  1968                                              PILOT

[100 rows x 2 columns]

In [18]:
from pandas.io.json import json_normalize
import pandas as pd
import json

responsedata = json.load(open('pl.json'))
array = []

for data in responsedata:
    array.append([data['year'], data['languageLabel']])
dataframe = pd.DataFrame(array, columns=['year', 'languageLabel']) 
dataframe = dataframe.astype(dtype= {"year":">i4", "languageLabel":"<U200"})

grouped = dataframe.groupby('year').count()
print(grouped)

grouped = dataframe.groupby('year').agg(['count'])
print(grouped.columns)

      languageLabel
year
1943              1
1946              2
1947              1
1948              3
1949              2
1950              3
1951             11
1952              4
1953              2
1954              6
1955              7
1956              2
1957              4
1958              5
1959              6
1960              4
1961              1
1962              5
1963              2
1964              9
1965              3
1966              9
1967              7
1968              1
MultiIndex(levels=[['languageLabel'], ['count']],
           labels=[[0], [0]])

In [86]:
from pandas.io.json import json_normalize
import pandas as pd
import json

jsondata = json.load(open('plparadigm.json'))
array = []

for data in jsondata:
    array.append([data['year'], data['languageLabel'], data['paradigmLabel']])
dataframe = pd.DataFrame(array, columns=['year', 'languageLabel', 'paradigmLabel']) 
dataframe = dataframe.astype(dtype= {"year":"int64", "languageLabel":"<U200", "paradigmLabel" : "<U200"})

grouped = dataframe.groupby(['year','paradigmLabel']).agg(['count'])
print(grouped)

grouped = dataframe.groupby(['paradigmLabel', 'year']).agg(['count'])
print(grouped)

                                            languageLabel
                                                    count
year paradigmLabel
1948 procedural programming                             1
1949 non-structured programming                         1
     procedural programming                             1
1950 procedural programming                             1
1953 procedural programming                             1
     structured programming                             1
1954 array programming                                  1
     generic programming                                1
     imperative programming                             2
     object-oriented programming                        1
     procedural programming                             1
     structured programming                             1
1955 imperative programming                             1
     procedural programming                             1
1956 assembly language                                  1
     procedural programming                             1
1957 array programming                                  1
     generic programming                                1
     imperative programming                             1
     object-oriented programming                        1
     procedural programming                             2
     structured programming                             1
1958 functional programming                             1
     imperative programming                             1
     metaprogramming                                    1
     multi-paradigm programming                         1
     procedural programming                             3
     reflective programming                             1
     structured programming                             1
1959 functional programming                             1
...                                                   ...
1962 multi-paradigm programming                         1
     object-oriented programming                        1
     structured programming                             1
1963 multi-paradigm programming                         1
     procedural programming                             1
1964 imperative programming                             3
     non-structured programming                         1
     procedural programming                             2
1966 array programming                                  1
     functional programming                             2
     imperative programming                             2
     modular programming                                1
     multi-paradigm programming                         2
     procedural programming                             5
     structured programming                             1
1967 functional programming                             1
     imperative programming                             1
     multi-paradigm programming                         2
     object-oriented programming                        1
     procedural programming                             2
1968 functional programming                             1
     pattern matching                                   1
     procedural programming                             3
1969 imperative programming                             1
     procedural programming                             1
1970 imperative programming                             1
     procedural programming                             1
     structured programming                             1
1971 functional programming                             1
     knowledge representation and reasoning             1

[73 rows x 1 columns]
                                            languageLabel
                                                    count
paradigmLabel                          year
array programming                      1954             1
                                       1957             1
                                       1962             1
                                       1966             1
assembly language                      1956             1
functional programming                 1958             1
                                       1959             1
                                       1962             1
                                       1966             2
                                       1967             1
                                       1968             1
                                       1971             1
generic programming                    1954             1
                                       1957             1
imperative programming                 1954             2
                                       1955             1
                                       1957             1
                                       1958             1
                                       1959             2
                                       1960             2
                                       1962             1
                                       1964             3
                                       1966             2
                                       1967             1
                                       1969             1
                                       1970             1
knowledge representation and reasoning 1971             1
metaprogramming                        1958             1
                                       1959             1
modular programming                    1962             1
...                                                   ...
object-oriented programming            1962             1
                                       1967             1
pattern matching                       1968             1
procedural programming                 1948             1
                                       1949             1
                                       1950             1
                                       1953             1
                                       1954             1
                                       1955             1
                                       1956             1
                                       1957             2
                                       1958             3
                                       1959             5
                                       1960             3
                                       1963             1
                                       1964             2
                                       1966             5
                                       1967             2
                                       1968             3
                                       1969             1
                                       1970             1
reflective programming                 1958             1
                                       1959             1
structured programming                 1953             1
                                       1954             1
                                       1957             1
                                       1958             1
                                       1962             1
                                       1966             1
                                       1970             1

[73 rows x 1 columns]

In [14]:
from pandas.io.json import json_normalize
import pandas as pd
import json

jsondata = json.load(open('population.json'))
array = []

for data in jsondata:
    array.append([data['year'], data['countryLabel'], data['population']])
dataframe = pd.DataFrame(array, columns=['year', 'countryLabel', 'population']) 
dataframe = dataframe.astype(dtype= {"year":"int64", "countryLabel" : "<U200", "population" :"int64"})

#grouped = dataframe.groupby(['countryLabel', 'year']).mean()
dataframe.loc[dataframe['countryLabel']=='Argentina'].sort_values('year', ascending=False)

     year countryLabel  population
364  2015    Argentina    43417000
381  2013    Argentina    41446246
337  2012    Argentina    41086927
375  2011    Argentina    40728738
343  2010    Argentina    40374224
349  2009    Argentina    40023641
356  2008    Argentina    39676083
366  2007    Argentina    39331357
357  2006    Argentina    38988923
360  2005    Argentina    38647854
345  2004    Argentina    38308779
338  2003    Argentina    37970411
385  2002    Argentina    37627545
333  2001    Argentina    37273361
374  2000    Argentina    36903067
363  1999    Argentina    36514558
370  1998    Argentina    36109342
376  1997    Argentina    35690778
336  1996    Argentina    35264070
341  1995    Argentina    34833168
369  1994    Argentina    21997888
382  1993    Argentina    33961947
348  1992    Argentina    33520803
335  1991    Argentina    33075194
378  1990    Argentina    32624874
344  1989    Argentina    32170407
365  1988    Argentina    31713147
368  1987    Argentina    31254574
371  1986    Argentina    30796481
362  1985    Argentina    30340419
377  1984    Argentina    29886564
380  1983    Argentina    29435404
339  1982    Argentina    28989069
373  1981    Argentina    28550123
330  1980    Argentina    28120135
340  1979    Argentina    27701412
350  1978    Argentina    27293093
347  1977    Argentina    26889764
386  1976    Argentina    26483835
355  1975    Argentina    26070443
367  1974    Argentina    25646533
358  1973    Argentina    25215328
331  1972    Argentina    24785830
332  1971    Argentina    24370660
353  1970    Argentina    23978532
383  1969    Argentina    23612675
372  1968    Argentina    23269302
334  1967    Argentina    22941477
384  1966    Argentina    22618887
361  1965    Argentina    22293817
352  1964    Argentina    21963952
351  1963    Argentina    21630854
342  1962    Argentina    21295290
346  1961    Argentina    20959241
359  1960    Argentina    20623998
354  1910    Argentina     7091822
379  1895    Argentina     3954911